### ISSUE TITLE
ST7735S 1.8 Inch LCD Does Not  Work

### ISSUE THREAD

**Issue by Peter-J-Jansen** [bitbank2/Pi_Pico_C_Projects#2]
Whereas a ST7789 1.14 LCD 240 x 135 display works perfectly, the ST7735S based one one does not.  My attempts the last 10 days or so to get this working all failed. As this is a 128 x 160 display, I produced an animated GIF of that size (from the AnimatedGIF repo), which also displays perfectly beautiful on the ST7789 LCD display. 

I presume the LCD type for the ST7735S display must be actually set to "ST7735R" (as it is a 128 x 160 display), but that too does not work. I also tried reducing the CLOCK_SPEED down to (12 * 1024 * 1024), but that too makes no difference. I presume the error is related to the use of DMA to actually perform GIFDraw, but could not debug it any further.

I'm using a Raspberry Pi 4B 8GB as development system for this Raspberry Pico + LCD displays, using VS Code as my IDE.

I understand your focus is on Arduino, but would be ever so thankful for suggestions as to how I could resolve my Pico problem with Animated GIF's for this ST7735S 1.8 inch display from Waveshare.

Thanks,

Peter

**Comment by bitbank2** [comment]
I've worked with a lot of these LCDs and sometimes the issue is that it wants to use SPI mode 3 instead of SPI mode 0. The SPI clock speed below 24Mhz should work on all of the variants. If you can initialize the LCD and see the random contents of memory on the display, then the library is doing the right thing and talking correctly to it. If you never see anything except a black screen, then it probably has nothing to do with DMA and the LCD is ignoring the commands you're sending it. Without the specific LCD in my hands, I'm afraid I can't help you beyond this info.
